<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE document [
        <!ENTITY project SYSTEM "project.xml">

        <!-- DTD is used to validate changelog structure at build time. BZ 64931. -->

        <!ELEMENT document (project?, properties, body)>
        <!ATTLIST document url CDATA #REQUIRED>

        <!-- body and title are used both in project.xml and in this document -->
        <!ELEMENT body ANY>
        <!ELEMENT title (#PCDATA)>

        <!-- Elements of project.xml -->
        <!ELEMENT project (title, logo, body)>
        <!ATTLIST project name CDATA #REQUIRED>
        <!ATTLIST project href CDATA #REQUIRED>

        <!ELEMENT logo (#PCDATA)>
        <!ATTLIST logo href CDATA #REQUIRED>

        <!ELEMENT menu (item+)>
        <!ATTLIST menu name CDATA #REQUIRED>

        <!ELEMENT item EMPTY>
        <!ATTLIST item name CDATA #REQUIRED>
        <!ATTLIST item href CDATA #REQUIRED>

        <!-- Elements of this document -->
        <!ELEMENT properties (author*, title, no-comments) >
        <!ELEMENT author (#PCDATA)>
        <!ATTLIST author email CDATA #IMPLIED>
        <!ELEMENT no-comments EMPTY>

        <!ELEMENT section (subsection)*>
        <!ATTLIST section name CDATA #REQUIRED>
        <!ATTLIST section rtext CDATA #IMPLIED>

        <!ELEMENT subsection (changelog+)>
        <!ATTLIST subsection name CDATA #REQUIRED>

        <!ELEMENT changelog (add|update|fix|scode|docs|design)*>
        <!ELEMENT add ANY>
        <!ELEMENT update ANY>
        <!ELEMENT fix ANY>
        <!ELEMENT scode ANY>
        <!ELEMENT docs ANY>
        <!ELEMENT design ANY>

        <!ELEMENT bug (#PCDATA)>
        <!ELEMENT rev (#PCDATA)>

        <!-- Random HTML markup tags. Add more here as needed. -->
        <!ELEMENT a (#PCDATA)>
        <!ATTLIST a href CDATA #REQUIRED>
        <!ATTLIST a rel CDATA #IMPLIED>

        <!ELEMENT b (#PCDATA)>
        <!ELEMENT code (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT tt (#PCDATA)>
        ]>
<?xml-stylesheet type="text/xsl" href="tomcat-docs.xsl"?>
<document url="changelog.html">

    &project;

    <properties>
        <title>Changelog</title>
        <no-comments/>
    </properties>

    <body>
        <!--
  Subsection ordering:
  General, Catalina, Coyote, Jasper, Cluster, WebSocket, Web applications,
  Extras, Tribes, jdbc-pool, Other

  Item Ordering:

  Fixes having an issue number are sorted by their number, ascending.

  There is no ordering by add/update/fix/scode/docs/design.

  Other fixed issues are added to the end of the list, chronologically.
  They eventually become mixed with the numbered issues (i.e., numbered
  issues do not "pop up" wrt. others).
-->
        <section name="Tomcat 8.5.61 (markt)">
            <subsection name="Catalina">
                <changelog>
                    <fix>
                        <bug>56181</bug>: Update the RemoteIpValve and RemoteIpFilter so that
                        calls to <code>ServletRequest.getRemoteHost()</code> are consistent with
                        the return value of <code>ServletRequest.getRemoteAddr()</code> rather
                        than always returning a value for the proxy. (markt)
                    </fix>
                    <fix>
                        <bug>56890</bug>: Align the behaviour of
                        <code>ServletContext.getRealPath(String path)</code>
                        with the recent
                        clarification from the Servlet specification project. If the path
                        parameter does not start with <code>/</code> then Tomcat processes the
                        call as if <code>/</code> is appended to the beginning of the
                        provided path. (markt)
                    </fix>
                    <fix>
                        <bug>64921</bug>: Ensure that the
                        <code>LoadBalancerDrainingValve</code>
                        uses the correct setting for the secure attribute for any session
                        cookies it creates. Based on a pull request by Andreas Kurth. (markt)
                    </fix>
                    <fix>
                        <bug>64947</bug>: Don't assume that the <code>Upgrade</code> header has
                        been set on the <code>HttpServletResponse</code> before any call is made
                        to <code>HttpServletRequest.upgrade()</code>. (markt)
                    </fix>
                    <fix>
                        Ensure that values are not duplicated when manipulating the vary header.
                        Based on a pull request by Fredrik Fall. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Coyote">
                <changelog>
                    <fix>
                        <bug>64944</bug>: Ensure that the bytesSent metric is correctly updated
                        when compression is enabled. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="WebSocket">
                <changelog>
                    <fix>
                        <bug>64951</bug>: Fix a potential file descriptor leak when WebSocket
                        connections are attempted and fail. Patch provided by Maurizio Adami.
                        (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Web applications">
                <changelog>
                    <fix>
                        Correct a regression in the addition of the HTTP header security filter
                        to the examples web application that prevented the Servlet examples that
                        depend on the asynchronous API from functioning correctly.
                        (kkolinko/markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Tribes">
                <changelog>
                    <scode>
                        Start all core threads when starting the receiver and dispatch
                        interceptor. (kfujino)
                    </scode>
                </changelog>
            </subsection>
            <subsection name="Other">
                <changelog>
                    <add>
                        <bug>64931</bug>: Implement validation of
                        <code>changelog.xml</code>
                        file at build time. (kkolinko)
                    </add>
                    <update>
                        Update to Maven Ant Resolver Tasks 1.3.0. (markt)
                    </update>
                    <fix>
                        <bug>62695</bug>: Provide SHA-256 and SHA-512 checksums for files
                        published via Maven. (markt)
                    </fix>
                </changelog>
            </subsection>
        </section>
        <section name="Tomcat 8.5.60 (markt)" rtext="2020-11-17">
            <subsection name="Catalina">
                <changelog>
                    <fix>
                        <bug>55559</bug>: Add a new attribute, <code>localJndiResource</code>,
                        that allows a UserDatabaseRealm to obtain a UserDatabase instance from
                        the local (web application) JNDI context rather than the global JNDI
                        context. This option is only useful when the Realm is defined on the
                        Context. (markt)
                    </fix>
                    <update>
                        Add connection pooling to JNDI realm. (remm)
                    </update>
                    <fix>
                        <bug>64805</bug>: Correct imports used by <code>JMXProxyServlet</code>.
                        (markt)
                    </fix>
                    <fix>
                        Fix JNDIRealm pooling problems retrying on another bad connection. Any
                        retries are made on a new connection, just like with the single
                        connection scenario. Also remove all connections from the pool after
                        an error. (remm)
                    </fix>
                    <fix>
                        JNDIRealm connections should only be created with the container
                        classloader as the thread context classloader, just like for the JAAS
                        realm. (remm)
                    </fix>
                    <add>
                        <bug>64871</bug>: Log a warning if Tomcat blocks access to a file
                        because it uses symlinks. (markt)
                    </add>
                    <update>
                        Rename <code>JDBCStore</code> to
                        <code>DataSourceStore</code>
                        and remove bottlenecks for database backed session store. The
                        <code>JDBCStore</code>
                        is deprecated but remains unchanged. Patch
                        submitted by Philippe Mouawad. (remm)
                    </update>
                </changelog>
            </subsection>
            <subsection name="Coyote">
                <changelog>
                    <fix>
                        Refactor the HTTP/2 window update handling for padding in data frames to
                        ensure that the connection window is correctly updated after a data
                        frame with zero length padding is received. (markt)
                    </fix>
                    <fix>
                        Fix processing of URIs with %nn encoded solidus characters when
                        <code>encodedSolidusHandling</code>
                        was set to
                        <code>passthrough</code>
                        and the encoded solidus was preceded by other %nn encoded characters.
                        Based on a pull request by willmeck. (markt)
                    </fix>
                    <fix>
                        <bug>63362</bug>: Add collection of statistics for HTTP/2, WebSocket and
                        connections upgraded via the HTTP upgrade mechanism. (markt)
                    </fix>
                    <add>
                        Provide messages for some <code>SocketTimeoutException</code> instances
                        that did not have one. (markt)
                    </add>
                    <add>
                        Add additional debug logging for I/O issues when communicating with the
                        user agent. (markt)
                    </add>
                    <fix>
                        <bug>64830</bug>: Fix concurrency issue in HPACK decoder. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="WebSocket">
                <changelog>
                    <fix>
                        <bug>64848</bug>: Fix a variation of this memory leak when a write I/O
                        error occurs on a non-container thread. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Web applications">
                <changelog>
                    <fix>
                        <bug>64799</bug>: Added missing resources to host-manager web app. (isapir)
                    </fix>
                    <fix>
                        <bug>64797</bug>: Align manager.xml template file in Host-Manager with
                        context.xml of real Manager web application. (isapir)
                    </fix>
                    <add>
                        Configure the examples web applications to set
                        <code>SameSite=strict</code>
                        for all cookies, including session cookies,
                        created by the application. (markt)
                    </add>
                    <add>
                        Configure the examples, Manager and Host Manager to use the HTTP header
                        security filter with default settings apart from no HSTS header. Based
                        on a suggestion by Debangshu Kundu. (markt)
                    </add>
                </changelog>
            </subsection>
            <subsection name="Other">
                <changelog>
                    <add>
                        Improvements to French translations. (remm)
                    </add>
                    <add>
                        Improvements to Korean translations. (woonsan)
                    </add>
                    <add>
                        Improvements to Russian translations. Provided by Azat. (markt)
                    </add>
                </changelog>
            </subsection>
        </section>
        <section name="Tomcat 8.5.59 (markt)" rtext="2020-10-09">
            <subsection name="Catalina">
                <changelog>
                    <fix>
                        Fix race condition when saving and recycling session in
                        <code>PersistentValve</code>. (kfujino)
                    </fix>
                    <update>
                        Deprecate the JDBCRealm. (markt)
                    </update>
                    <fix>
                        Correct numerous spellings throughout the code base. Based on a pull
                        request from John Bampton. (markt)
                    </fix>
                    <fix>
                        <bug>64715</bug>: Add PasswordValidationCallback to the JASPIC
                        implementation. Patch provided by Robert Rodewald. (markt)
                    </fix>
                    <fix>
                        Throw <code>SQLException</code> instead of
                        <code>NullpointerException</code>
                        when failing to connect to the
                        database. (kfujino)
                    </fix>
                    <fix>
                        <bug>64735</bug>: Ensure that none of the methods on a
                        <code>ServletContext</code>
                        instance always fail when running under a
                        SecurityManager. Pull request provided by Kyle Stiemann. (markt)
                    </fix>
                    <fix>
                        <bug>64765</bug>: Ensure that the number of currently processing threads
                        is tracked correctly when a web application is undeployed, long running
                        requests are being processed and
                        <code>renewThreadsWhenStoppingContext</code>
                        is enabled for the web
                        application. (markt)
                    </fix>
                    <add>
                        Improve the error messages when running under JPMS without the necessary
                        options to enable reflection required by the memory leak prevention /
                        detection code. (markt)
                    </add>
                    <fix>
                        When estimating the size of a resource in the static resource cache,
                        include a specific allowance for the path to the resource. Based on a
                        pull request by blueSky1825821. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Coyote">
                <changelog>
                    <fix>
                        Do not send an HTTP/2 PING frame to measure round-trip time when it is
                        known that the HTTP/2 connection is not in a good state. (markt)
                    </fix>
                    <fix>
                        <bug>64743</bug>: Correct a regression introduced in 8.5.57 that
                        caused a <code>Connection: close</code> header to be added to the
                        response if the Connector was configured with
                        <code>maxSwallowSize=-1</code>. (markt)
                    </fix>
                    <fix>
                        When logging HTTP/2 debug messages, use consistent formatting for stream
                        identifiers. (markt)
                    </fix>
                    <fix>
                        Correct some double counting in the code that tracks the number of
                        in-flight asynchronous requests. The tracking enables Tomcat to shutdown
                        gracefully when asynchronous processing is in use. (markt)
                    </fix>
                    <fix>
                        Don't send the Keep-Alive response header if the connection has been
                        explicitly closed. (markt)
                    </fix>
                    <fix>
                        Refactor the handling of closed HTTP/2 streams to reduce the heap usage
                        associated with used streams and to retain information for more streams
                        in the priority tree. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Jasper">
                <changelog>
                    <fix>
                        Use lazy instantiation to improve the performance when working with
                        listeners added to the <code>ELContext</code>. Pull request provided by
                        Thomas Andraschko. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Web applications">
                <changelog>
                    <add>
                        Configure the Manager and Host Manager applications to set
                        <code>SameSite=strict</code>
                        for all cookies, including session cookies,
                        created by the application. (markt)
                    </add>
                    <fix>
                        Update the Manager How-To in the documentation web application to
                        clarify when a user may wish to deploy additional instances of the
                        Manager web application. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Other">
                <changelog>
                    <update>
                        Update to Commons Daemon 1.2.3. This adds support to jsvc for
                        <code>--enable-preview</code>
                        and native memory tracking (Procrun
                        already supported these features), adds some addition debug logging and
                        adds a new feature to Procrun that outputs the command to (re-)configure
                        the service with the current settings. (markt)
                    </update>
                    <add>
                        When building, only rebuild JAR files if the contents has changed.
                        (markt)
                    </add>
                    <add>
                        Improvements to Chinese translations. Pull request provided by Yang
                        Yang. (markt)
                    </add>
                    <add>
                        Expand coverage of Russian translations. Pull request provided by
                        Nikolay Gribanov. (markt)
                    </add>
                    <fix>
                        Fix running service.bat when called from <code>$CATALINA_HOME</code>.
                        (markt)
                    </fix>
                    <fix>
                        Complete the fix for <bug>63815</bug>. Users wishing to use system
                        properties that require quoting with <code>catalina.sh</code> and the
                        <code>debug</code>
                        option must use a JRE that includes the fix for <a
                            href="https://bugs.openjdk.java.net/browse/JDK-8234808">JDK-8234808</a>.
                        (markt)
                    </fix>
                    <add>
                        Improvements to Chinese translations. Provided by leeyazhou. (markt)
                    </add>
                    <add>
                        Improvements to French translations. (remm)
                    </add>
                    <add>
                        Improvements to Korean translations. (woonsan)
                    </add>
                    <add>
                        Improvements to Spanish translations. Provided by Andrewlanecarr.
                        (markt)
                    </add>
                </changelog>
            </subsection>
        </section>
        <section name="Tomcat 8.5.58 (markt)" rtext="2020-09-15">
            <subsection name="Catalina">
                <changelog>
                    <fix>
                        <bug>53411</bug>: Improve the handling of HTTP requests that do not
                        explicitly specify a host name when no default host is configured. Also
                        improve the tracking of changes to the default host as hosts are added
                        and removed while Tomcat is running. (markt)
                    </fix>
                    <fix>
                        <bug>64582</bug>: Pre-load the <code>CoyoteOutputStream</code> class to
                        prevent a potential exception when running under a security manager.
                        Patch provided by Johnathan Gilday. (markt)
                    </fix>
                    <fix>
                        <bug>64593</bug>: If a request is not matched to a Context, delay
                        issuing the 404 response to give the rewrite valve, if configured, an
                        opportunity to rewrite the request. (remm/markt)
                    </fix>
                    <add>
                        Refactor the Default servlet to provide a single method that can be
                        overridden (<code>generateETag()</code>) should a custom entity tag
                        format be required. (markt)
                    </add>
                    <fix>
                        Improve the validation of entity tags provided with conditional
                        requests. Requests with headers that contain invalid entity tags will be
                        rejected with a 400 response code. Improve the matching algorithm used
                        to compare entity tags in conditional requests with the entity tag for
                        the requested resource. Based on a pull request by Sergey Ponomarev.
                        (markt)
                    </fix>
                    <fix>
                        Correct the description of the storage format for salted hashes in the
                        Javadoc for <code>MessageDigestCredentialHandler</code> and refactor the
                        associated code for clarity.
                        Based on a patch provided by Milo van der Zee. (markt)
                    </fix>
                    <fix>
                        Correct the path validation to allow the use of the file system root for
                        the <code>docBase</code> attribute of a <code>Context</code>. Note that
                        such a configuration should be used with caution. (markt)
                    </fix>
                    <add>
                        Added filtering expression for requests that are not supposed to use
                        session in <code>PersistentValve</code>. (kfujino)
                    </add>
                    <fix>
                        Use the correct method to calculate session idle time in
                        <code>PersistentValve</code>. (kfujino)
                    </fix>
                    <fix>
                        <bug>64712</bug>: The JASPIC authenticator now checks the
                        <code>ServerAuthModule</code>
                        for
                        <code>jakarta.servlet.http.authType</code>
                        and, if present, uses the
                        value provided. Based on a patch by Robert Rodewald. (markt)
                    </fix>
                    <fix>
                        <bug>64713</bug>: The JASPIC authenticator now checks the value of
                        <code>jakarta.servlet.http.registerSession</code>
                        set by the
                        <code>ServerAuthModule</code>
                        when deciding whether or nor to register
                        the session. Based on a patch by Robert Rodewald. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="Coyote">
                <changelog>
                    <add>
                        <bug>57661</bug>: For requests containing the
                        <code>Expect: 100-continue</code>
                        header, add optional support to delay
                        sending an intermediate 100 status response until the servlet reads the
                        request body, allowing the servlet the opportunity to respond without
                        asking for the request body. Based on a pull request by malaysf. (markt)
                    </add>
                    <fix>
                        Refactor the implementation of
                        <code>ServletInputStream.available()</code>
                        to provide a more accurate
                        return value, particularly when end of stream has been reached. (markt)
                    </fix>
                    <fix>
                        <bug>64614</bug>: Improve compatibility with FIPS keystores. When a FIPS
                        keystore is configured and the keystore contains multiple keys, the
                        alias attribute will be ignored and the key used will be implementation
                        dependent. (jfclere)
                    </fix>
                    <fix>
                        <bug>64621</bug>: Improve handling HTTP/2 stream reset frames received
                        from clients. (markt)
                    </fix>
                    <fix>
                        <bug>64660</bug>: Avoid a potential NPE in the AprEndpoint if a socket
                        is closed in one thread at the same time as the poller is processing an
                        event for that socket in another. (markt)
                    </fix>
                    <fix>
                        <bug>64671</bug>: Avoid several potential NPEs introduced in the changes
                        in the previous release to reduce the memory footprint of closed HTTP/2
                        streams. (markt)
                    </fix>
                    <fix>
                        Refactor the HTTP/2 implementation to more consistently return a stream
                        closed error if errors occur after a stream has been reset by the
                        client. (markt)
                    </fix>
                    <fix>
                        Improve handling of HTTP/2 stream level flow control errors and notify
                        the stream immediately if it is waiting for an allocation when the flow
                        control error occurs. (markt)
                    </fix>
                    <fix>
                        Ensure that window update frames are sent for HTTP/2 connections to
                        account for DATA frames containing padding including when the associated
                        stream has been closed. (markt)
                    </fix>
                    <fix>
                        Ensure that window update frames are sent for HTTP/2 connections and
                        streams to account for DATA frames containing zero-length padding.
                        (markt)
                    </fix>
                    <fix>
                        <bug>64710</bug>: Revert the changes to reduce the memory footprint of
                        closed HTTP/2 streams as they triggered multiple regressions in the form
                        of <code>NullPointerException</code>s. (markt)
                    </fix>
                    <fix>
                        Ensure that the HTTP/2 overhead protection check is performed after
                        each HTTP/2 frame is processed. (markt)
                    </fix>
                </changelog>
            </subsection>
            <subsection name="WebSocket">
                <changelog>
                    <fix>
                        Requests received via proxies may be marked as using the
                        <code>ws</code>
                        or <code>wss</code> protocol rather than <code>http</code> or
                        <code>https</code>. Ensure that such requests are not rejected. PR
                        provided by Ronny Perinke. (markt)